CREATE DATABASE VENTAS_TIENDA;
USE VENTAS_TIENDA;

CREATE TABLE PRODUCTOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODIGO CHAR(5),
NOMBRE VARCHAR (30),
PRECIO DOUBLE,
CANTIDAD INT
);
CREATE TABLE CLIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODIGO CHAR(5),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(30),
DNI CHAR(8),
SEXO VARCHAR(10),
DISTRITO VARCHAR(30)
);
CREATE TABLE VENDEDOR (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
EDAD VARCHAR(3),
GENERO VARCHAR(30),
DISTRITO VARCHAR(50)
);

CREATE TABLE DISTRITO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30),
DESCRIPCION TEXT
)

SELECT*FROM PRODUCTOS
SELECT*FROM clientes
SELECT*FROM vendedor

